language: android
sudo: required
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - extra-android-support
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  licenses:
  - .+
before_install:
- openssl aes-256-cbc -K $encrypted_83fcb329e442_key -iv $encrypted_83fcb329e442_iv
  -in app/google-services.json.enc -out app/google-services.json -d
- chmod +x gradlew
script:
- cd $TRAVIS_BUILD_DIR/
- ./gradlew build jacocoTestReport
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
